/**
 * This file was automatically generated by Modelarium
 * on {{date}}
 */

export default [
    {
        path: '/{{lowerName}}',
        name: '{{StudlyName}}List',
        component: {{ StudlyName }}List
    },
    {
        path: '/{{lowerName}}/:id',
        name: '{{StudlyName}}Show',
        component: {{ StudlyName }}Show
    },
    {
        path: '/{{lowerName}}/:id/edit',
        name: '{{StudlyName}}Edit',
        component: {{ StudlyName }}Edit
    },
    {
        path: '/{{lowerName}}/edit',
        name: '{{StudlyName}}Edit',
        component: {{ studlyName }}Edit
    }
];

