<?php
/**
 * This file was automatically generated by Modelarium.
 */

/** @var \Illuminate\Database\Eloquent\Factory $factory */
use Faker\Generator as Faker;

$factory->define(App\DummyName::class, function (Faker $faker) {
    return App\DummyName::getRandomData();
});
