<?php
/**
 * This file was automatically generated by Modelarium on {{date}}
 */

namespace Database\Factories;

use App\Models\{|studlyName|};
use Illuminate\Database\Eloquent\Factories\Factory;

class {|studlyName|}Factory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = {|studlyName|}::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return {|studlyName|}::getRandomData();
    }
}
