<?php
/**
 * This file was automatically generated by Modelarium.
 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDummyNameTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('dummytablename', function (Blueprint $table) {
            // dummyCode
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('dummytablename');
    }

    public function model(): string
    {
        return <<<EOF
modelSchemaCode
EOF;
    }
}
