<?php
/**
 * This file was automatically generated by Modelarium 
 * Please do not change or you may break later migration patches.
 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class {|className|}Table extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::{|upOperation|}('{|dummytablename|}', function (Blueprint $table) {
            {|&dummyCode|}
        });
        {|&dummyPostCreateCode|}
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::{|downOperation|}('{|dummytablename|}'{|#if dummyInverseCode|}, function (Blueprint $table) {
            {|&dummyInverseCode|}
        }{|/if|});
    }

    /**
     * The graphql model used to generate this migration. This will be used for
     * patching later.
     */
    public function model(): string
    {
        return <<<EOF
{|&modelSchemaCode|}
EOF;
    }
}
