<?php
/**
 * This file was automatically generated by Modelarium. Please do not change
 * or you may break later migration patchhes.
 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDummyNameTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('dummytablename', function (Blueprint $table) {
            // dummyCode
        });
        // dummyPostCreateCode
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('dummytablename');
    }

    /**
     * The graphql model used to generate this migration. This will be used for
     * patching later.
     */
    public function model(): string
    {
        return <<<EOF
modelSchemaCode
EOF;
    }
}
