<?php
/**
 * This file was automatically generated by Modelarium.
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class DummyClass extends {{ParentDummyModel}}
{
    {{traitsCode}}

    protected $fillable = {{dummyFillable}};
    
    protected $hidden = {{dummyHidden}};

{{dummyMethods}}
}
