<?php
/**
 * This file was automatically generated by Modelarium.
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class BaseDummyClass extends {{ParentDummyModel}}
{
    {{traitsCode}}

    protected $fillable = {{dummyFillable}};
    
    protected $hidden = {{dummyHidden}};

    public function getRandom(): array {
        return [];
    }

{{dummyMethods}}
}
