<?php
/**
 * This file was automatically generated by Modelarium.
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class BaseDummyClass extends {{ParentDummyModel}}
{
    {{traitsCode}}

    protected $fillable = {{dummyFillable}};
    
    protected $hidden = {{dummyHidden}};

    public function getFormularium(): \Formularium\Model
    {
        $model = new \Formularium\Model('DummyClass');
{{fieldsCode}}
        $model->appendFields($fields);
        return $model;
    }

    public function getRandom(): array 
    {
        return $this->getFormularium->getRandom();
    }

{{dummyMethods}}
}
