<?php declare(strict_types=1);
/**
 * This file was automatically generated by Modelarium
 */

use Illuminate\Database\Seeder;

class {|StudlyName|}Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $model = factory(App\Models\{|StudlyName|}::class)->create();
        {|{ extraCode }|}
    }
}
