<?php
/**
 * This file was automatically generated by Modelarium.
 */

use Illuminate\Database\Seeder;

class {|StudlyName|}Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        factory(App\{|StudlyName|}::class)->create();
    }
}
