<template> </template>

<script>
/**
 * This file was automatically generated by Modelarium.
 */
import FormulariumBase from './FormulariumBase';

export default {
    extends: FormulariumBase,

    data() {
        return {
            type: '{{modelName}}',
            fields: {{jsonData}}
        };
    }
};
</script>
<style></style>
