<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-12-20T12:01:19-03:00.
 */

namespace Modelarium\Types;

class Datatype_cpf extends FormulariumScalarType
{
}
