<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-12-20T15:23:35-03:00.
 */

namespace Modelarium\Types;

class Datatype_alphanum extends FormulariumScalarType
{
}
