<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-12-20T12:02:52-03:00.
 */

namespace Modelarium\Types;

class Datatype_ipv4 extends FormulariumScalarType
{
}
