<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-12-18T15:09:25-03:00.
 */

namespace Modelarium\Types;

class Datatype_html extends FormulariumScalarType
{
}
