<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-12-11T17:01:12-03:00.
 */

namespace Modelarium\Types;

class Datatype_currency extends FormulariumScalarType
{
}
