<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-12-10T19:15:33-03:00.
 */

namespace Modelarium\Types;

class Datatype_bool extends FormulariumScalarType
{
}
