<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-12-03T16:03:30-03:00.
 */

namespace Modelarium\Types;

class Datatype_domain extends FormulariumScalarType
{
}
