<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-12-07T12:27:00-03:00.
 */

namespace Modelarium\Types;

class Datatype_languageiso2 extends FormulariumScalarType
{
}
