<?php declare(strict_types=1);

namespace Modelarium\Laravel\Targets;

use GraphQL\Type\Definition\NonNull;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;
use Modelarium\GeneratedCollection;
use Modelarium\GeneratedItem;
use Nette\PhpGenerator\ClassType;

class EventGenerator extends BaseGenerator
{
    /**
     * @var ObjectType
     */
    protected $type = null;

    /**
     * @var GeneratedCollection
     */
    protected $events;

    public function generate(): GeneratedCollection
    {
        $this->events = new GeneratedCollection();
        
        foreach ($this->type->getFields() as $field) {
            $directives = $field->astNode->directives;
            $this->processDirectives($field, $directives);
        }
        return $this->events;
    }

    protected function makeEventClass(string $name, string $model): GeneratedItem
    {
        $eventTokens = explode('\\', $name);
        $eventClassName = array_pop($eventTokens);
        $eventNamespace = implode('\\', $eventTokens);
        $relativePath = implode('/', $eventTokens);

        $namespace = new \Nette\PhpGenerator\PhpNamespace($eventNamespace);

        /**
         * @var ClassType $class
         */
        $class = $namespace->addClass($eventClassName);
        $class
            ->addComment("This file was automatically generated by Modelarium.")
            ->setTraits(['Illuminate\Queue\SerializesModels']);
        
        $class->addProperty('target')
            ->setPublic()
            ->setComment("@var $model");
        $printer = new \Nette\PhpGenerator\PsrPrinter;
    
        $constructor = $class->addMethod('__construct');
        $constructor->setPublic()
            ->addParameter('target')
            ->setType('App\\' . $model);

        $constructor->addBody(
            '$this->target = $target;'
        );

        return new GeneratedItem(
            $name,
            "<?php declare(strict_types=1);\n\n" . $printer->printNamespace($namespace),
            $this->getGenerateFilename($relativePath, $eventClassName)
        );
    }

    public function processDirectives(
        \GraphQL\Type\Definition\FieldDefinition $field,
        \GraphQL\Language\AST\NodeList $directives
    ): void {
        if ($field->type instanceof NonNull) {
            $type = $field->type->getWrappedType();
        } else {
            $type = $field->type;
        }
        $typeName = $type->name; /** @phpstan-ignore-line */
        
        foreach ($directives as $directive) {
            $name = $directive->name->value;
            switch ($name) {
            case 'event':
                $dispatch = '';
                
                foreach ($directive->arguments as $arg) {
                    /**
                     * @var \GraphQL\Language\AST\ArgumentNode $arg
                     */

                    $value = $arg->value->value;

                    switch ($arg->name->value) {
                    case 'dispatch':
                        $dispatch = $value;
                    break;
                    }
                }
                $e = $this->makeEventClass($dispatch, $typeName);
                $this->events->push($e);
                break;
            default:
            }
        }
    }

    public function getGenerateFilename(string $relativePath, string $name): string
    {
        // fix App -> app
        if (substr($relativePath, 0, 3) === 'App' && !is_dir($this->getBasePath($relativePath))) {
            $relativePath[0] = 'a';
        }
        return $this->getBasePath($relativePath . '/' . $name . '.php');
    }
}
