<?php declare(strict_types=1);

namespace Modelarium\Laravel\Targets;

use GraphQL\Type\Definition\ObjectType;
use Modelarium\BaseGenerator;
use Modelarium\Exception\Exception;
use Modelarium\FormulariumUtils;
use Modelarium\GeneratedCollection;
use Modelarium\GeneratedItem;
use Modelarium\Parser;

class SeedGenerator extends BaseGenerator
{
    /**
     * @var string
     */
    protected $stubDir = __DIR__ . "/stubs/";

    /**
     * Extra seed code generated by parser
     *
     * @var string[]
     */
    public $extraCode = [];

    public function generate(): GeneratedCollection
    {
        if (!($this->type instanceof ObjectType)) {
            throw new Exception('Invalid type on seed generator:' . get_class($this->type));
        }

        /**
         * @var \GraphQL\Language\AST\NodeList|null
         */
        $directives = $this->type->astNode->directives;
        if ($directives) {
            $this->processTypeDirectives($directives, 'Seed');
        }

        /**
         * @var ObjectType $t
         */
        $t = $this->type;
        foreach ($t->getFields() as $field) {
            $directives = $field->astNode->directives;
            $this->processFieldDirectives($field, $directives, 'Seed');
        }

        return new GeneratedCollection(
            [ new GeneratedItem(
                GeneratedItem::TYPE_SEED,
                $this->generateString(),
                $this->getGenerateFilename()
            )]
        );
    }


    public function generateString(): string
    {
        return $this->templateStub(
            'seed',
            [
                'extraCode' => join("\n", $this->extraCode)
            ]
        );
    }

    public function getGenerateFilename(): string
    {
        return $this->getBasePath('database/seeds/'. $this->studlyName . 'Seeder.php');
    }
}
